### PR TITLE
Add license to package metadata

### PR DESCRIPTION
**Pull request by ecederstrand**

### CODE REVIEW

**Comment by ecederstrand** [comment]
@CamDavidsonPilon Ping?

**Comment by CamDavidsonPilon** [comment]
wowow totally missed this, sorry @ecederstrand! 

PR lgtm, need me to ship a new version to pypi, too?

**Comment by ecederstrand** [comment]
No problem 🙂 A new version would be great!

**Comment by CamDavidsonPilon** [comment]
https://pypi.org/project/autograd-gamma/ should be 0.4.3 - let me know if you need something else

**Pull request merged**
